remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Predicting League of Legends Match Outcomes
description: Based on some factors that can be recorded during a game, can you predict the outcome of a League of Legends game while it's in progress?